### ISSUE TITLE
Allow to specify input file

### ISSUE THREAD

**Issue by Al2Klimov** [Al2Klimov/trainee-php-sort#3]
... so that `php sort.php in.txt` does the same as `sort in.txt`.

**Comment by Yonas-net** [comment]
#3 issue solved

**Comment by Al2Klimov** [comment]
Don't close issues even if you think that you're done if you work not on master. Come to me and I'll explain you how do do that better.

**Comment by Al2Klimov** [comment]
By the way I've not assigned this to you, yet.
